//
// Created by Alienson on 3.2.2024..
//

#ifndef WINTER_ROUTER_H
#define WINTER_ROUTER_H

/**
 * Contains all endpoints. They are registered on startup and the code for it is generated by preprocessor. The code is
 * contained in each controller class. Currently it is done by initializing a static variable with a lambda function so
 * creating additional instances if controllers may lead to multiple instances of endpoint being added to the array
 */

#include <memory>
#include <utility>
#include "Reflect.h"
#include "mutex"
#include "../http/HttpRequest.h"
#include "../http/HttpResponse.h"
#include "../util/ThreadPool.h"

class Endpoint{
public:
    Endpoint() : method(nullptr), func(nullptr){}
    Endpoint(const char* url, HttpMethod* _method, std::function<HttpResponse*(HttpRequest*)>& f) : method(_method), uri(url), func(std::move(f)){}
    HttpMethod* method;
    URI uri;
    std::function<HttpResponse*(HttpRequest*)> func;
};

class Router {
public:
    Router(Router& other) = delete;
    void operator=(const Router&) = delete;
    static Router* getInstance();

    void routeRequest(shared_ptr<HttpRequest> &request);
    void registerEndpoint(Endpoint* endpoint);
    void registerEndpoint(const char* url, HttpMethod* _method, std::function<HttpResponse*(HttpRequest*)> f);
    void initializeEndpoints(){}

    vector<Endpoint*> endpoints;

private:
    Router() = default;
    ~Router();
    ThreadPool threadPool{20};
    static Router* instance;
    static mutex mutex_;
};


#endif //WINTER_ROUTER_H
